### ISSUE TITLE
HCL plugin is broken with Intellij IDEA 2021.2 

### ISSUE THREAD

**Issue by xfournet** [VladRassokhin/intellij-hcl#349] opened 2021-07-27 20:53 UTC
Thank you for opening an issue.
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`) 
```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Licensed to YOOI / Xavier Fournet
You have a perpetual fallback license for this version.
Subscription is active until January 5, 2023.
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 8
Registry: nodejs.console.use.terminal=false
Non-Bundled Plugins: com.intellij.ideolog (203.0.27.0), org.intellij.plugins.hcl (0.7.10), com.intellij.plugin.adernov.powershell (2.0.7), Pythonid (212.4746.92), aws.toolkit (1.29-212), zielu.gittoolbox (212.6.6), org.intellij.scala (2021.2.15)
Kotlin: 212-1.5.10-release-IJ4746.92
```

 - [x] intellij-hcl plugin version (`Settings->Plugins`)
```0.7.10```

 - [x] Terraform version (`terraform -v`)
```
Terraform v1.0.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.51.0
```

### Terraform Configuration Files
```hcl
terraform {
  required_version = "1.0.3"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.51.0"
    }
  }
}

resource "aws_s3_bucket" "this" {
  bucket = "hcl-plugin-is-broken"
  force_destroy = true

  versioning {
    enabled = true
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}

data "aws_iam_policy_document" "this" {
  statement {
    sid = "AllowSSLRequestsOnly"
    effect = "Deny"
    principals {
      type = "*"
      identifiers = ["*"]
    }
    actions = ["s3:*"]
    resources = [
      aws_s3_bucket.this.arn,
      "${aws_s3_bucket.this.arn}/*"
    ]
    condition {
      test = "Bool"
      variable = "aws:SecureTransport"
      values = [false]
    }
  }
}

resource "aws_s3_bucket_policy" "this" {
  bucket = aws_s3_bucket.this.id
  policy = data.aws_iam_policy_document.this.json
}
```

### Expected Behavior
File is valid, no warning or errors should be reported by the IDE. It was working correctly with previous IDEA version

### Actual Behavior
* All resource attribute are in error
* All resource sub blocks are in warning
* No autocompletion
![Screenshot 2021-07-27 225052](https://user-images.githubusercontent.com/461943/127225529-ab7431bb-c7ab-4558-bcbf-2171bbd2fb4b.png)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a main.tf file in IDEA with the content above
2. See the warning and errors
3. See completion is not working

**Comment by lukvdborne** [comment] 2021-07-29 07:03
I tried it with the stable build and have them same issue.

```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Licensed to xxx
Subscription is active until August 12, 2021.
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5
GC: G1 Young Generation, G1 Old Generation
Memory: 1536M
Cores: 8
Registry: search.everywhere.settings=true
Non-Bundled Plugins: YAML/Ansible support (0.11.2), com.intellij.apacheConfig (212.4746.57), com.intellij.plugins.watcher (212.4746.52), org.intellij.plugins.hcl (0.7.10), org.jetbrains.plugins.localization (212.4746.57), org.jetbrains.plugins.rest (212.4746.57), AWSCloudFormation (212.4746.57), com.intellij.lang.puppet (212.4746.57), org.toml.lang (0.2.151.3997-212), org.elixir_lang (11.10.0), Pythonid (212.4746.96), org.jetbrains.plugins.ruby (212.4746.92), com.intellij.plugins.html.instantEditing (212.4746.57), com.jetbrains.php (212.4746.92), org.jetbrains.plugins.go (212.4746.92), org.rust.lang (0.4.151.3997-212)
Kotlin: 212-1.5.10-release-IJ4746.92
```

**Comment by rviniandrade** [comment] 2021-07-29 15:11
I have the same issue here. How can we roll back the update?

`PyCharm 2021.2 (Community Edition)
Build #PC-212.4746.96, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.0-8-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 984M
Cores: 8
Non-Bundled Plugins: org.intellij.plugins.hcl (0.7.10), ru.adelf.idea.dotenv (2021.2.212)
Current Desktop: KDE`

**Comment by lukvdborne** [comment] 2021-07-30 06:45
@rviniandrade I just rolled back using the Toolbox

<img width="435" alt="image" src="https://user-images.githubusercontent.com/2690390/127612183-6ffcd6ba-a245-4112-a8d7-6798e02e2a3a.png">

**Comment by rviniandrade** [comment] 2021-07-30 18:05
> @rviniandrade I just rolled back using the Toolbox
> 
> <img alt="image" width="435" src="https://user-images.githubusercontent.com/2690390/127612183-6ffcd6ba-a245-4112-a8d7-6798e02e2a3a.png">

Thank you very much @lukvdborne

**Comment by billylaing** [comment] 2021-08-02 18:28
Same issue here.

**Comment by kwitkow** [comment] 2021-08-03 07:32
Confirmed

IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Licensed to ***
You have a perpetual fallback license for this version.
Subscription is active until July 31, 2022.
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: org.intellij.plugins.hcl (0.7.10), com.atlassian.bitbucket.references (2021.2.171), com.intellij.kubernetes (212.4746.57), com.demonwav.minecraft-dev (2021.2-1.5.12), Pythonid (212.4746.96), com.jetbrains.php (212.4746.100)
Kotlin: 212-1.5.10-release-IJ4746.92

**Comment by Fran-E** [comment] 2021-08-04 06:28
Same issue for me with 2021.2. Rollback on 2021.1.4 done.

Do we have news about this? 

Thanks in advance.

**Comment by craigday** [comment] 2021-08-05 02:59
Same issue here.

IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Non-Bundled Plugins: FrameSwitcher (3.26.1-203), Statistic (4.1.7), io.snyk.snyk-intellij-plugin (2.2.1), org.intellij.plugins.hcl (0.7.10), String Manipulation (8.15.203.000.3), com.dmarcotte.handlebars (212.4746.57), Dart (212.4746.57), io.flutter (59.0.4), io.kanro.idea.plugin.protobuf (1.4.1)
Kotlin: 212-1.5.10-release-IJ4746.92

**Comment by kwitkow** [comment] 2021-08-05 09:02
Rollback is problematic because lots of plugins are also updated and do not work with previous version of IntelliJ :(

**Comment by billylaing** [comment] 2021-08-07 19:54
Update: This started working for me again. I confirmed I have the same version of PyCharm and the plugin installed.

```
PyCharm 2021.2 (Professional Edition)
Build #PY-212.4746.96, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins: org.intellij.plugins.hcl (0.7.10)
```

**Comment by G-Rath** [comment] 2021-08-09 03:08
I believe 2021.2 made some changes to indexing that meant pre 2021.2 indexes got thrown out - you should be able to fix this issue by reloading the terraform module:

![image](https://user-images.githubusercontent.com/3151613/128656588-5f6efaf2-8aa1-43da-907f-c1af7442e617.png)

**Comment by Fran-E** [comment] 2021-08-09 06:30
Thanks G-Rath,  reloading the terraform module solve this problem but, for me, it's required at each start. I think there is still something wrong?

**Comment by G-Rath** [comment] 2021-08-09 06:52
@Fran-E ugh yeah I get that too when restarting - and [JetBrains don't care](https://youtrack.jetbrains.com/issue/PY-49332).

**Comment by hazmeister** [comment] 2021-08-12 12:24
> Thanks G-Rath, reloading the terraform module solve this problem but, for me, it's required at each start. I think there is still something wrong?

Additionally, I need to close and re-open my project (without fully quitting IntelliJ) after reloading the module.  But as other commenters have said, this only seems to last until you relaunch IntelliJ.

**Comment by jeremysmitherman** [comment] 2021-08-14 11:19
The model reload works for the current session, but breaks again on restart.  Is there anything we can do to help debug this?

**Comment by sergei-ivanov** [comment] 2021-08-17 09:55
I opted for a simple way out: I rolled my IntelliJ IDEA back to 2021.1. It was a bit of a hassle, but working Terraform plugin is more important to me than any new features in 2021.2. Lack of commitment on the part of JetBrains is really disappointing here. If they don't have resources to support the plugin, they should offer the stewardship to HashiCorp and give the source code back to the community.

**Comment by cob16** [comment] 2021-08-20 10:33
Note after you have opened a project If you disable and re-enable the plugin it seems to work again :shrug:

**Comment by rajaie-sg** [comment] 2021-08-24 15:55
I emailed JetBrains support asking about the plugin and got this response 

> Responsible developer is working on the compatibility issue with the latest IntelliJ IDE release. We'll release a new version of the plug-in in a few weeks. Sorry for the inconvenience.

**Comment by alejandrod-f** [comment] 2021-08-28 22:02
Same issue here. Mental note: Do not ever upgrade IntelliJ too fast. Is a terrible experience... It always have issues.
I can confirm that it's fixed with the reload thing as described by @G-Rath Thanks!!

**Comment by timja** [comment] 2021-09-03 09:29
Looks like a new release is out

**Comment by VladRassokhin** [comment] 2021-09-03 13:39
Fixed in 0.7.11+

**Closed by VladRassokhin** 2021-09-03 13:39 UTC

**Comment by zerubeus** [comment] 2021-12-29 01:09
this is not fixed at all still have the same problem

**Comment by ikarlashov** [comment] 2022-01-04 16:53
@VladRassokhin It's broken (again?).

Plugin version: 0.7.14
Intellij version: 2021.2
macOS Monterey 12.0.1

**Comment by 0xFate** [comment] 2022-01-06 00:44
> this is not fixed at all still have the same problem, I'm in 0.7.14
same issue on 0.7.14
Terraform v1.1.2

**Comment by timja** [comment] 2022-01-06 07:54
This issue was fixed I suggest opening a new issue rather than commenting on an old one.

**Comment by VladRassokhin** [comment] 2022-01-06 14:20
Please open new issue indeed with more details than "it's broken", that isn't helpful.
