### ISSUE TITLE
Error during writing aws_iam_policy rules

### ISSUE THREAD

**Issue by fniko** [VladRassokhin/intellij-hcl#256] opened 2019-09-05 12:51 UTC
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
IntelliJ IDEA 2019.2.1 (Ultimate Edition)
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
0.7.5
 - [x] Terraform version (`terraform -v`)
Terraform v0.12.7

### Terraform Configuration Files
```hcl
resource "aws_iam_policy" "policy" {
  name = "test_policy"
  description = "My Policy"
  path = "/"

  policy = <<EOF
  {
    "Policy Config Here"
  }

}
```

### Exception
```text
None
```

### Expected Behavior
What should have happened?
I should be able to work with the "JSON" with working syntax highlight.
https://www.terraform.io/docs/providers/aws/r/iam_policy.html

### Actual Behavior
What actually happened?
Error appears:
```hcl
<boolean>, <expression>, <heredoc>, <null>, <number>, <string literal> or HD_START expected got '<<'
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Start creating aws_iam_policy
2. Write the exact policy rules

**Comment by VladRassokhin** [comment] 2019-09-05 12:53
Just add closing heredoc marker and it would gone.

**Closed by VladRassokhin** 2019-09-05 12:53 UTC

**Comment by fniko** [comment] 2019-09-05 12:57
Resolves the error related issue, but syntax highlight still not working.

**Comment by VladRassokhin** [comment] 2019-09-06 06:31
There's no highlighting inside heredocs by design since it could be any arbitrary language

**Comment by fniko** [comment] 2019-09-06 10:16
OK, got it, thank you!
