### ISSUE TITLE
Terraform TypeMaps are incorrectly formatted

### ISSUE THREAD

**Issue by benosman** [VladRassokhin/intellij-hcl#260] opened 2019-09-20 22:14 UTC
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19)
 - [x] intellij-hcl plugin version (0.7.6)
 - [x] Terraform version (v0.12.9)

### Expected Behavior
The autocomplete should insert TypeMap declared items into the code as arguments like below: 
```
triggers = {
    serial = "2019-09-20"
}

tags = {
  environment = "develop"
}
```
### Actual Behavior
The autocomplete should insert TypeMap declared items into the code as blocks, which fail in `terraform apply` with an error.

```
triggers {
    serial = "2019-09-20"
}

tags {
  environment = "develop"
}
```
#### Error
`Blocks of type "<name>" are not expected here. Did you mean to define argument "<name>"? If so, use the equals sign to assign it a value.`

Additionally, if you manually add the equals sign to make it work, from then on the HCL plugin does not recognise that map's subkeys in the autocompletion popup.

**Comment by benosman** [comment] 2019-09-20 22:18
There is another related issue for an older version:
https://github.com/VladRassokhin/intellij-hcl/issues/233

**Comment by VladRassokhin** [comment] 2019-09-22 16:33
Closing as duplicate of #233

**Closed by VladRassokhin** 2019-09-22 16:33 UTC
