### ISSUE TITLE
Multiple quotes in line breaks formatting/inspection

### ISSUE THREAD

**Issue by wpg4665** [VladRassokhin/intellij-hcl#44] opened 2016-08-21 22:31 UTC
Example from Terraform documentation (https://www.terraform.io/docs/providers/google/index.html) causes breakage when providing credentials as such:

`credentials = "${file("account.json")}"`

**Comment by VladRassokhin** [comment] 2016-08-22 09:48
Don't see any line breaks in you example.

**Comment by wpg4665** [comment] 2016-08-22 10:51
Sorry, I apologize, the multiple quotes cause the issue where everything after that line is not properly formatted. Let me show you a screen shot of what I mean.

Here is a screen shot with formatting broken:
![image](https://cloud.githubusercontent.com/assets/621376/17852312/a6cde30a-6834-11e6-914d-985767bb9792.png)


Now, if I remove the extra quotes around K8Trial-baa15f7c351c.json, it correctly formats:
![image](https://cloud.githubusercontent.com/assets/621376/17852333/c88042e0-6834-11e6-86ea-1eda91ce768a.png)


However, without the double quotes, Terraform throws a Syntax error and won't accept the file. Did that help explain my issue better??

**Comment by VladRassokhin** [comment] 2016-08-24 12:13
Thanks, screenshots helps. Will fix in next version.
You're using Terraform 0.7, right?

**Comment by wpg4665** [comment] 2016-08-24 12:17
Great! Yes, the newest, 0.7.2 I believe =)

**Comment by VladRassokhin** [comment] 2016-08-24 12:19
So far I cannot reproduce issue using intellij-hcl plugin version 0.5.7.
Is file named as '*.tf' and has 'Terraform' file type?
File type could be checked in next way:
* Reveal file in project view window
* Use context menu action 'Mark as plain text', see highlighting changed
* Use context menu action 'Mark as Terraform'. There should be that action, not 'Mark as HCL'

**Comment by wpg4665** [comment] 2016-08-24 14:23
Wow, totally my fault!! When I first started with Terraform, I didn't have
your extension installed, so I picked "Plain Text" when I opened it the
first time. After installing your extension, I had to manually re-assign
the file type, and since the HCL type was the first I found, I picked that
one. Wow, I'm sorry. Thanks again! =)

**Closed** 2016-08-24 14:23 UTC

**Comment by VladRassokhin** [comment] 2016-08-24 15:40
Ok, no problems.
HCL just not supports interpolations, so parser works a bit different.
