### ISSUE TITLE
Escaped Quotes break highlight/inspection

### ISSUE THREAD

**Issue by EntilZha** [VladRassokhin/intellij-hcl#35] opened 2016-07-30 17:19 UTC
Looks like if I have something like this, it will mark it as an error:

```
provisioner "remote-exec" {
    inline = ["echo \"export CONF=${var.value}\" >> /home/ubuntu/.bashrc"]
  }
```

The backslashes cause the error

**Comment by VladRassokhin** [comment] 2016-07-30 18:19
Seems it's duplicate of #34 or fixed within that issue.

**Closed by VladRassokhin** 2016-07-30 18:19 UTC
