### ISSUE TITLE
latest release of pycharm won't run the plugin

### ISSUE THREAD

**Issue by ketzacoatl** [VladRassokhin/intellij-hcl#126] opened 2017-12-04 05:01 UTC
I downloaded `0.6.9.2` and unpacked the plugin into my pycharm install. When I load the plugin, I see this from pycharm, in the console:
```
WARN: HashiCorp Terraform / HCL language support not loaded: until build 173.2000 < PC-173.3727.137
```
Pycharm is a new/clean install, downloaded tonight.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)

```
PyCharm 2017.3 (Community Edition)
Build #PC-173.3727.137, built on November 28, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

 - [x] intellij-hcl plugin version (`Settings->Plugins`)
 - [x] Terraform version (`terraform -v`)

`0.10.8`

Is there something I need to do to use the HCL plugin with the lastest release of pycharm?

**Comment by VladRassokhin** [comment] 2017-12-04 19:12
Duplicate of #125

**Closed by VladRassokhin** 2017-12-04 19:12 UTC
